import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
//   display: "swap",
//   fallback: ["system-ui", "arial"],
// });

export const metadata: Metadata = {
  title: "Move Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` font-sans antialiased relative min-h-screen`}
      >
        {children}

        <div className="absolute bottom-0 left-0 w-full ">
          <img
            src="/images/Vectors.svg"
            alt="Bottom vector"
            className="w-full h-full object-contain"
          />
        </div>
      </body>
    </html>
  );
}
